
POST http://localhost:11434/api/embeddings 
{
  "model": "mixtral",
  "prompt": "Here is an article about llamas..."
}


###
POST http://localhost:6333/collections/demo/points/search
Content-Type: application/json

{
    "vector": [0.2,0.1,0.9,0.7],
    "top": 3
}



###

GET http://localhost:6333/collections/demo

###
GET http://localhost:6333/collections/demo/points/1

